pipeline {
    agent none
    triggers {
        cron('H/15 * * * *')
    }

    environment {
        FOO = "bar"
    }

    stages {
        stage("echo") {
    	    agent {
    	    	kubernetes {
      		    cloud 'kubernetes'
      		    label 'ubuntupod'
      		    yamlFile 'podspecs/ubuntu.yaml'
    		        }
	        }
	        steps {
	    	    container('ubuntu') {
                      sh "echo hello"
		       }
		   }
	    }
    }
}
